### ISSUE TITLE
Followed install guide — fail

### ISSUE THREAD

**Issue by BsNoSi** [redtide/yellow-simplemde-plugin#1]
It seems not to be as simple as described. I copied the files to plugins but nothing happend.

**Comment by redtide** [comment]
Weird, I just tried now to do it in a fresh yellow install and it worked, it replaces the original editor textarea :-/

**Comment by BsNoSi** [comment]
maybe it is quite simple: Is a installed version of the editor, you pointed out, required (this is not mentioned in install guide)?

If yes: can it simply copied to the plugin area or is the install setup as described there required?

**Comment by redtide** [comment]
What do you mean with an installed version? Those 2 files needs only to be copied as described in the image and the editor will work replacing the original one, nothing else.
The php adds the required SimpleMDE files from CDN, the js file creates it in place of the original editor textarea.
- Have you tried with a fresh yellow install and copied the files in system/plugins?
- Which browser system are you using?
- Maybe you copied the .png image file in place of .php? :smile:

**Comment by BsNoSi** [comment]
Ok - good hint: I tried with "Vivaldi", uses same engine as Chrome (I tried, too). These both do not show anything. Trying with Firefox works.

But it is not that nice for me as expected: Because of German text, everything is marked as wrong.
Second challenge: If text exceeds the page, it is not possible to scroll to the save/cancel buttons.
Third challenge: It is not predictable, wether a new text is created or an existing one is displayed in the editor.

**Comment by redtide** [comment]
I tried here with chrome and it showed me the original editor textarea for the first time, maybe the js script was loaded after its download when the page was already displayed.
I'm going to disable the spellChecker.

**Comment by redtide** [comment]
I disabled the spellchecker now, if you want to retry let me know all issues you can find, I see there are some others to check (e.g. here both cursor and text selection are invisible).
Closing this issue, the others you have found were moved.

**Comment by BsNoSi** [comment]
Sorry for delay: 
1. vivaldi/Chrome still do not load plug in (tried several times)
2. Firefox loads plug in but edit loads only headline, no content.
   - Clicking into edit area loads content
   - content is not editable (sometimes, but I did not find the technique, to have control over the process)
   - Text area can not scroll, long text extends window (no exit/save button)
   - New loads previously edited text, but not editable

This is my current status. Because nothing is editable, any further testing is not possible.

**Comment by redtide** [comment]
I tried to make a plugin for markdownify too and it seems that there are some issues to make work JS editors against Yellow editor textarea.
It looks like to me that we miss some event handling, some communication back from the plugin and the webinterface (resizing, update/refresh the custom JS editor in sync with the original textarea).

**Comment by redtide** [comment]
Thank you for testing BTW :smile:
